---
title: Piráti Česká Třebová
timezone: UTC
collections:
  elections:
    title: Elections
    output: true
    permalink: "/volby/:path/"
  people:
    title: People
    output: true
    permalink: "/lide/:path/"
  posts:
    title: Posts
    output: true
  program:
    title: Program
    output: true
    permalink: "/volby-2018/program/:title/"
  teams:
    title: Teams
    output: true
    permalink: "/pripoj-se/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _people
  values:
    layout: page
    rbar: people, foto
- scope:
    path: _program/komunal2018
  values:
    layout: page
    rbar: program
- scope:
    path: _program/psp2017
  values:
    layout: page
    rbar: program program_item
- scope:
    path: _teams
  values:
    layout: team
    rbar: team-summary, teams-toc
- scope:
    path: _elections
  values:
    layout: kandidatka
email: pardubicko@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií
  21. století pro otevřenou demokratickou společnost.
baseurl: 
url: http://ceskatrebova.pirati.cz
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
paginate_path: "/aktuality/:num/"
paginate: 11
exclude:
- readme.md
- Gemfile
- Gemfile.lock
- package.json
- bower.json
- gulpfile.js
- node_modules
- bower_components
- vendor
sass:
  style: compressed
permalink: "/tiskove-zpravy/:title.html"
calendar: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=kddvdvu3adcjef2kro4j6mm838%40group.calendar.google.com&amp;color=%232952A3&amp;ctz=Europe%2FPrague
fb_name: 'Piráti Česká Třebová '
fb: https://www.facebook.com/piratiCT/
tw: PiratskaStrana
instagramm: https://www.instagram.com/pirati.cz/
gplus: https://plus.google.com/u/0/+piratskastrana
peoplesOnForum: https://forum.pirati.cz/pardubicky-kraj-g35.html
